# Site settings
title: ChileBit.NET
email: contacto@chilebit.net
description: > # this means to ignore newlines until "baseurl:"
  ChileBit - La primera exchange de Bitcoin en Chile.   
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chilebit.net" # the base hostname & protocol for your site
twitter_username: chilebit
github_username: chilebit
facebook_username: chilebit.net

# Build settings
markdown: kramdown
